### ISSUE TITLE
iPhone SE (2020) ?

### ISSUE THREAD

**Issue by jvanakker** [lmirosevic/GBDeviceInfo#110]
iPhone SE (2020) ?
This should be: iPhone12,8

Not sure what most common name is, "iPhone SE 2020" or "iPhone SE 2nd generation". For now, I added it like this:
```
// iPhone SE 2020
@[@12, @8]: @[@(GBDeviceModeliPhoneSE2), @"iPhone SE 2020", @(GBDeviceDisplay4p7Inch), @326],
```

**Comment by lmirosevic** [comment]
We merged it in as `GBDeviceModeliPhoneSE2 ` in the end.

PS sorry for the late comment.
