### ISSUE TITLE
v6.5.0 - fatal error: 'GBDeviceInfo/GBDeviceInfo.h' file not found

### ISSUE THREAD

**Issue by phillipc-myfiziq** [lmirosevic/GBDeviceInfo#118]
Looks like the recent Swift Package update moved the GBDeviceInfo.h file without updating the podspec file. 

Specifically in PR: https://github.com/lmirosevic/GBDeviceInfo/commit/e638ecc751846eebcfdde1c54edd426db68b5441

Was this intentional, and if so, should the podspec and readme example be updated with the new import?

Thank you.

**Comment by dcollens** [comment]
I think the podspec needs to add Public/GBDeviceInfo.h?

**Comment by MingzhiYe** [comment]
I also faced this problem. @dcollens @phillipc-myfiziq

**Comment by lmirosevic** [comment]
Just published @phillipc-myfiziq 's fix as `6.5.1`.

Thanks a lot for the fast PR!

Please let me know if there's any other issues and I'll try to push an update ASAP.

**Comment by phillipc-myfiziq** [comment]
@lmirosevic yep, no problem, thank you.
