### ISSUE TITLE
Heads: DeviceFamily probably won't be reliable on some newer Macs

### ISSUE THREAD

**Issue by cpsauer** [lmirosevic/GBDeviceInfo#134]
Hey, @lmirosevic.

I happened to notice that some newer macs have a strange change in their model identifiers. The [M2 13" MBP, for example is "Mac14,7"](https://support.apple.com/en-us/HT201300) and the [M2 Air is "Mac14,2"](https://support.apple.com/en-us/HT201862). This doesn't seem to be a typo in Apple's docs, because [this twitter thread backs it up](https://twitter.com/thecomputerclan/status/1548085287586123777). [Mac studio is similar](https://support.apple.com/en-us/HT213073). I think that's the full list for now, unless I'm forgetting something. (iMacs and M1 chips all retain sane names.)

That'd require some changes to the code for device family to fix--or at least a comment to warn people. Maybe we should hardcode the correct families--or there's a more robust future proof way that's backing the text in the image in the twitter thread?

Anyway, thought I should raise it for discussion.

Thanks for your consideration,
Chris

Code below for reference:
https://github.com/lmirosevic/GBDeviceInfo/blob/d958909c2590a861769ce665be11b008dac6bbda/GBDeviceInfo/GBDeviceInfo_OSX.m#L152-L182

**Comment by lmirosevic** [comment]
That's a good observation!

My thinking is to do something along the lines of:

```objective-c
else if ([systemInfoString hasPrefix:@"MacPro"]) { 
    return GBDeviceFamilyMacPro;
} 
else if (
            [systemInfoString hasPrefix:@"MacBookPro"] ||
            [systemInfoString hasPrefix:@"Mac14,7"]
        ) { 
    return GBDeviceFamilyMacBookPro;
} 

else if (
            [systemInfoString hasPrefix:@"MacBookAir"] ||
            [systemInfoString hasPrefix:@"Mac14,2"]
        ) { 
    return GBDeviceFamilyMacBookAir;
}
```

It isn't the prettiest. But the alternatives that I can think of all basically boil down to abstracting this syntax into a simpler form using a roundabout approach like making a mapping, and then writing some code that will take the systemInfoString and apply the mapping to it to get the correct enum. However that will complicate the code for little benefit IMHO. I've also considered an alternative with regexes, but again that adds reader-complexity that I'm not sure is warranted.

What do you think @cpsauer ?

**Comment by cpsauer** [comment]
Seems reasonable to me--but let me see quickly if I can find an alternate public API for us to hit.
