### ISSUE TITLE
Dispatch_once?

### ISSUE THREAD

**Issue by hfossli** [lmirosevic/GBDeviceInfo#14]
Why isn't this wrapped in dispatch_once?

https://github.com/lmirosevic/GBDeviceInfo/blob/master/GBDeviceInfo/GBDeviceInfo_iOS.m#L87

**Comment by christophercotton** [comment]
I would also love a dispatch_once since we use it to check which version of iOS we are on for UI items. How about just making those properties which can vary at runtime, be properties that call those methods directly each time?

**Comment by christophercotton** [comment]
And I'd be happy to do some of the work if you tell me which ones you want to be dynamic.

**Comment by lmirosevic** [comment]
That would be great.

This is the static/dynamic list I came up with, where static ones can be cached, and dynamic ones should be looked up each time.
ios:

rawSystemInfoString
deviceVersion
modelString
family
model
display
cpuInfo
physicalMemory
osVersion

osx:

static:
rawSystemInfoString
family
deviceVersion
physicalMemory
systemByteOrder
osVersion
isMacAppStoreAvailanle
isIAPAvailable

dynamic:
nodeName
cpuInfo
displayInfo

**Comment by lmirosevic** [comment]
Implemented in #25 and available on CocoaPods as 3.x

Special thanks to @christophercotton
