### ISSUE TITLE
Please add latest iPhones to the list. 

### ISSUE THREAD

**Issue by Shubhashree97** [lmirosevic/GBDeviceInfo#150]
Hi team, 
Please add these devices also to the list iPhone 15, 15 pro, 15 pro max, 15 plus.
Using GBDevice info in many places in my project. need support

**Comment by cpsauer** [comment]
All solved with #147! (Just got write permissions to the repo :)

**Comment by cpsauer** [comment]
For my learning, Shubhashree: What are you building with this library and using it for? How do you bring it and other deps into your project, if not cocoapods?
