### ISSUE TITLE
Detect iOS simulator device type

### ISSUE THREAD

**Issue by PokerChang** [lmirosevic/GBDeviceInfo#18]
Is it possible to detect device type for iOS simulator?  e.g. iPhone 6 simulator?

**Comment by lmirosevic** [comment]
Not that I can tell, but would be open to merging code if it were possible.

**Comment by capezzbr** [comment]
I think you now can with

```swift
        if let simulatorModelIdentifier = ProcessInfo().environment["SIMULATOR_MODEL_IDENTIFIER"] { return simulatorModelIdentifier }
        var sysinfo = utsname()
        uname(&sysinfo) // ignore return value
        return String(bytes: Data(bytes: &sysinfo.machine, count: Int(_SYS_NAMELEN)), encoding: .ascii)!.trimmingCharacters(in: .controlCharacters)
```

**Comment by philipengberg** [comment]
@lmirosevic would you consider this solutions? It would an *amazing* upgrade when working with custom layouts in the simulator 🙌

**Comment by philipengberg** [comment]
Never mind, migrated to https://github.com/anatoliyv/AssistantKit instead

**Comment by houmie** [comment]
> iPhone10,3

Sorry how does it indicate that this is a simulator? I'm doing it on iPhone 11 Simulator and I get `iPhone12,1`.  Thanks
