### ISSUE TITLE
Incorrect Device Info for OSX 10.10.1 - Minor OS Version

### ISSUE THREAD

**Issue by rolandhordos** [lmirosevic/GBDeviceInfo#22]
Hi, I noticed that your OS X operating system version info comes by way of a uname call.  It looks like the Darwin kernel information is not a reliable way to do this, at least as of Yosemite .1.

On various 10.10.1 Macs we all see:

    mymac:~ me$ uname -a
    Darwin mymac 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64

Which is consistent with the 0 minor os version returned by GBDeviceInfo.

May I suggest basing your version string on the system version plist instead?  Something like:

    NSString *systemVersion = [NSDictionary dictionaryWithContentsOfFile:@"/System/Library/CoreServices/SystemVersion.plist"][@"ProductUserVisibleVersion"];

**Comment by lmirosevic** [comment]
Fixed by b237f1bd1129ec7c11ae572cb0b6443caf4454bd

**Comment by lmirosevic** [comment]
Now on cocaapods as 3.0.0
