### ISSUE TITLE
Identifying Apple Watch?

### ISSUE THREAD

**Issue by SRandazzo** [lmirosevic/GBDeviceInfo#27]
First, thanks! GBDeviceInfo has served us well for a while now

I am curious if the Apple Watch is something that can be identified?

I know there's a bit of a strange case because the watch extensions run on the phone, so technically it's still being executed on an iPhone. Any insight/thoughts on this?

Thanks again!

**Comment by lmirosevic** [comment]
Hi, I'm glad you find the library useful, thanks!

Unfortunately I don't have any insights into detecting whether an app is running on an iPhone/iPad with a watch extension as I haven't built anything for the apple watch yet. 

Having said that I would be more than happy to update the library to support some apple watch detection modalities.
