### ISSUE TITLE
jailbroken status

### ISSUE THREAD

**Issue by developerJohn** [lmirosevic/GBDeviceInfo#28]
What method do you use to check if a device is Jailbroken?

**Comment by lmirosevic** [comment]
It's a closed source component thats dynamically and randomly injected at runtime so as to make it harder to reverse engineer and/or path at runtime.

The checks are a mix of checking for out-of-sandbox path access, common jailbroken installed apps like cydia etc, loaded dylibs, and a few more of the common checks. I'm being intentionally vague here. 

I've just submitted the HEAD version of the library to the App Store in one of the higher profile apps I publish along with some instrumentation to get real world data and verify that the verification works well. I am comparing it to the crashlytics jailbreak detection as the ground truth. If the numbers match I will cut a release of the library, for now the jailbreak stuff is still "alpha" if you will. 

Also, if you have any input re. jailbreak detection, I'd love to hear it!

**Comment by paramaggarwal** [comment]
The author has chosen to keep that closed source for obvious reasons: https://github.com/lmirosevic/GBJailbreakDetection
