### ISSUE TITLE
armv7s linker issue

### ISSUE THREAD

**Issue by iomark** [lmirosevic/GBDeviceInfo#30]
Hello. 

Thank you for excellent library.

I tried to use GBDeviceInfo in my project and got following issue presented on screenshot. Could you please help to resolve it. Seem it is related with using GBJailbreakDetection.framework. GBDeviceInfo with version 3.1 does not contain this one.

![screen shot 2015-06-30 at 2 04 03 pm](https://cloud.githubusercontent.com/assets/1295212/8429600/dc79cb24-1f31-11e5-9921-8073ded2ace6.png)

**Comment by lmirosevic** [comment]
You can resolve this by setting your projects architectures to `$(ARCHS_STANDARD)` which includes: armv7 and arm64

**Comment by lmirosevic** [comment]
And version `3.1` doesn't include jailbreak detection, so you must be referring to `3.2`
