### ISSUE TITLE
Unable to use via Cocoapods with use_frameworks!

### ISSUE THREAD

**Issue by stepanhruda** [lmirosevic/GBDeviceInfo#31]
Cocoapods is now able to build pods as dynamic frameworks, which is necessary for compiling Swift dependencies. I just tried updating GBDeviceInfo, but get this error:

`[!] The 'Pods-Foo' target has transitive dependencies that include static binaries: (/[PATH_TO_FOO]/Pods/GBJailbreakDetection/GBJailbreakDetection.framework)`

**Comment by earltedly** [comment]
I'm seeing this too

**Comment by tbaranes** [comment]
+1

**Comment by earltedly** [comment]
@stepanhruda I've downgraded to 3.0.0 in the meantime

**Comment by lmirosevic** [comment]
Will look into this. You should be able to use `3.1.0` as well in the meantime, as jailbreak detection was only added in `3.2.0`.

**Comment by earltedly** [comment]
@lmirosevic thanks :)

**Comment by stepanhruda** [comment]
I'll test this out today with 0.39.1.beta.

**Comment by nicolaidahl** [comment]
Any solution to this coming up?

**Comment by rodriguise** [comment]
+1, just need to the 6s support dont care about jailbreaks.

**Comment by lmirosevic** [comment]
`3.5.1` now supports use_frameworks!

Jailbreak detection has been made optional and moved into a subspec
