### ISSUE TITLE
Bitcode issue in iOS 9

### ISSUE THREAD

**Issue by poojanjhaveri** [lmirosevic/GBDeviceInfo#32]
libGBDeviceInfo.a(GBDeviceInfo_Common.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by n3trino** [comment]
Any update on this issue?

**Comment by lmirosevic** [comment]
Should be fixed in the dependency, please do a `pod update` and look for an update of `GBJailbreakDetection` to `1.1.0`
