### ISSUE TITLE
bitcode support

### ISSUE THREAD

**Issue by ajkiosd** [lmirosevic/GBDeviceInfo#35]
ld: bitcode bundle could not be generated because '.../Pods/GBJailbreakDetection/GBJailbreakDetection.framework/GBJailbreakDetection(GBJailbreakDetection.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

xcode 7.0.1

**Comment by lmirosevic** [comment]
Jailbreak detection has been made optional, so if you're not using it then updating to `3.5.1` should fix this issue.
