### ISSUE TITLE
GBDeviceInfo description is dependent upon the Jailbreak sub spec

### ISSUE THREAD

**Issue by JHumphreyJr** [lmirosevic/GBDeviceInfo#37]
Simply logging the device info without the Jailbreak sub spec raises an exception.

[GBDeviceInfo_iOS.m#L63](https://github.com/lmirosevic/GBDeviceInfo/blob/e85c0b205dd4fef635f7936e26bf4aa342bbc020/GBDeviceInfo/GBDeviceInfo_iOS.m#L63).

Example:

    NSLog(@"%@", [GBDeviceInfo deviceInfo]);

**Comment by lmirosevic** [comment]
You're absolutely right. Fixed in `3.5.1`
