### ISSUE TITLE
CocoaPods can't add version 3.5? Can you do me a favor to fix it?

### ISSUE THREAD

**Issue by wenzhishen** [lmirosevic/GBDeviceInfo#40]
Hi, in my podfile I type the line

    pod 'GBDeviceInfo', '~> 3.5' 

just as you said in github. But can't install successfully. here are the error information:

    [!] Unable to satisfy the following requirements:
    - `GBDeviceInfo (~> 3.5)` required by `Podfile`
I need this project in my App to adapt the newest iPhone 6S and Plus. Thanks!

**Comment by lmirosevic** [comment]
Try `pod update`
