### ISSUE TITLE
Separate Simulator device models

### ISSUE THREAD

**Issue by Jules2010** [lmirosevic/GBDeviceInfo#41]
It would be nice to be able to test different device configurations on the simulator rather than them being included as a separate device aka GBDeviceModelSimulatoriPhone or GBDeviceModelSimulatoriPad

**Comment by lmirosevic** [comment]
I don't think it is possible to distinguish between different device models inside a simulator. One could do it by screen size, but then it's still ambiguous between iPhone 5 vs iPhone 5S vs iPhone 5C, etc.
