### ISSUE TITLE
Can't install specified version of GBDeviceInfo with Cocoapods

### ISSUE THREAD

**Issue by wenzhishen** [lmirosevic/GBDeviceInfo#43]
Here is content of my Podfile:
    
    platform :ios, '6.0'
    pod 'GBDeviceInfo', '~> 3.5'
    pod 'GBDeviceInfo/Jailbreak', '~> 3.5'

But after executing `pod install`, it responsed this:

![screen shot 2016-01-21 at 10 24 49 am](https://cloud.githubusercontent.com/assets/15153965/12470061/0f85baf0-c02c-11e5-84c1-f2fd5e0b79f7.png)

Neither the search results contain the specified version `3.5`, as you can see in this snapshot above.

**Comment by lmirosevic** [comment]
Strange. Can you try 3.6?

**Comment by roma86** [comment]
Confirm. Also dragging manually to the swift project not working. Have multiple errors like "CGFloat not found".

**Comment by wenzhishen** [comment]
@lmirosevic , I tried, but still didn't work, generating the same error.
