### ISSUE TITLE
Support iPod

### ISSUE THREAD

**Issue by javorosas** [lmirosevic/GBDeviceInfo#45]
Hi. I'm getting "Unknown device" on the last gen iPod Touch. I've been debugging and the device version is (major = 7, minor = 1), but this library only supports until 5,1.

It would be nice that if you don't support a certain model, at least let us know what device it is. For example, iPad12,8 (non-existing yet) might return just iPad..

**Comment by lmirosevic** [comment]
It's now supported in the latest `3.8.0`. Please `pod update`.
