### ISSUE TITLE
pod search issues

### ISSUE THREAD

**Issue by charmingQin** [lmirosevic/GBDeviceInfo#56]
when I use pod search in the terminal

![2016-09-19 3 25 32](https://cloud.githubusercontent.com/assets/9345412/18625011/3e8cf7c6-7e7e-11e6-8b78-ffa3f7f23a2a.png)

**Comment by lmirosevic** [comment]
You are searching the local repo which is not up to date with the master repo.

`pod repo update`

**Comment by charmingQin** [comment]
ok, thanks, I will try

**Comment by charmingQin** [comment]
yes it works!!!   my repo is up to date !!
