### ISSUE TITLE
Jailbreak Detection

### ISSUE THREAD

**Issue by forsan** [lmirosevic/GBDeviceInfo#61]
Hi,
Thank you for your amazing framework.

I used GBJailbreakDetection (1.3.0) and GBDeviceInfo (3.8.0) in my project.
in the latest release in my project I add isJailbroken and its working fine in development, but after I submit my release to the app store, I found many issues in Crashlytics like the **image attached** and some users told me their devices not jailbroken but they can't use the app because the app told them you use Jailbroken device.

The crash in Crashlytics it is normal?
Note: When isJailbroken true i show msg alert for the user and when he click on the button I use exit() func to close the app.

<img width="975" alt="screen shot 2016-12-18 at 8 41 37 am" src="https://cloud.githubusercontent.com/assets/1745621/21291783/f8ccbd40-c4fd-11e6-9eeb-2d9b6b5e37cf.png">

**Comment by lmirosevic** [comment]
If you use `exit()` in case of a jailbroken device then this does look normal. Screenshot also confirms that it's a jailbroken device using Crashlytics' own detection code.
