### ISSUE TITLE
Any plans for tvos support?

### ISSUE THREAD

**Issue by HaseebYousaf** [lmirosevic/GBDeviceInfo#63]
I have used GBDeviceInfo in alot of projects over the years. However, in a recent project that had alot of common code between iOS and TVOS, i had to remove the pod. Do you have any plans for adding TVOS support?

**Comment by lmirosevic** [comment]
Submit a PR! And I I'll review it promptly. 

Sent from my mobile device.

--

Luka Mirosevic | Founder | luka@goonbee.com | +43 664 5412921

Goonbee e.U.
Neustiftgasse 108/9, A-1070 Wien
FN 394906w

This email and its attachments may be confidential, privileged and protected from disclosure. If you received this communication by mistake, please don't forward it to anyone else, please erase all copies and attachments, and please let me know that it went to the wrong person. Thanks.
