### ISSUE TITLE
Not working on iPad simulator ?

### ISSUE THREAD

**Issue by dtomicAZ** [lmirosevic/GBDeviceInfo#66]
It's look like this lib is not working on iOS iPad simulator:

I executed this code on iPad Pro (10.5-inch) simulator 10.3.1:
    if GBDeviceInfo.deviceInfo().family == .familyiPad {
      print("IPAD")
    }
and it's prints nothing.

I don't know if this is working on really device because currently I don't have one.

**Comment by lmirosevic** [comment]
A simulator is a simulator, not a real device. Actually there is no way to know inside the simulator which device is being simulated, so we don't really have many other options here than to call all simulators "a simulator".
