### ISSUE TITLE
Errors when building without precompiled headers

### ISSUE THREAD

**Issue by vshashenko** [lmirosevic/GBDeviceInfo#69]
We incorporate the source code of the library into a large project, which we build using cmake. Since cmake doesn't officially support precompiled headers yet, we don't use them. This causes compilation errors on iOS because of a missing include for UIKit, which is only included from the PCH file. It's trivial to fix and we patched the code, but I'm just letting you know about this use case. Maybe you'll want to do something about it so the library can be used flawlessly in cmake/non-PCH setups.

**Comment by lmirosevic** [comment]
👍
