### ISSUE TITLE
property not found on object of type GBDeviceInfo

### ISSUE THREAD

**Issue by MichaelGofron** [lmirosevic/GBDeviceInfo#76]
When I try reproing the code from the example I get the following error:

property "nodeName" not found on object of type 'GBDeviceInfo'
property "cpu" not found on object of type 'GBDeviceInfo'

I've imported the library into my file. I'm not sure why it doesn't seem to see it. 
Are these properties only available for mac? I'm trying to run on iOS simulator.

**Comment by lmirosevic** [comment]
Yes those are only available on macOS
