### ISSUE TITLE
Please add iPad 6 Gen 2018

### ISSUE THREAD

**Issue by vGubriienko** [lmirosevic/GBDeviceInfo#81]
Hi, when we could get an update with a latest iPad?

**Comment by lmirosevic** [comment]
Feel free to submit a PR and I will check+merge ASAP. 

Sent from my mobile device.

--

Luka Mirosevic | Founder | luka@goonbee.com | +43 664 5412921

Goonbee e.U.
Neustiftgasse 108/9, A-1070 Wien
FN 394906w

This email and its attachments may be confidential, privileged and protected from disclosure. If you received this communication by mistake, please don't forward it to anyone else, please erase all copies and attachments, and please let me know that it went to the wrong person. Thanks.

**Comment by vGubriienko** [comment]
Submitted the PR. @lmirosevic  Please review.

**Comment by lmirosevic** [comment]
Thanks for the PR

Pushed to CocoaPods as 5.2.0

**Comment by vGubriienko** [comment]
Thanks!
