### ISSUE TITLE
GBDeviceDisplay is always Unknown.

### ISSUE THREAD

**Issue by RobMans426** [lmirosevic/GBDeviceInfo#86]
GBDeviceDisplay display = [GBDeviceInfo deviceInfo].displayInfo.display;

when I print display info, it is always "GBDeviceDisplayUnknown" in the simulator.

Is this normal in the simulator?
Will it work in the real devices?

**Comment by lmirosevic** [comment]
That's expected behaviour on the simulator.

Real devices will return real display info.

**Comment by ricsantos** [comment]
Hmmm sounds like this is working as expected. I was hoping to be able to use the `model` and `display` properties in both the simulator and on device.
