### ISSUE TITLE
Update GBCPUInfo to support different frequencies for big.LITTLE cpus?

### ISSUE THREAD

**Issue by Diarrhio** [lmirosevic/GBDeviceInfo#87]
Latest iOS devices since the iPhone X have cores that don't have the same frequency, where there are two "fast" cores and four "slow" or low power cores. Do you have any plans to retrieve that info? Thanks!

**Comment by lmirosevic** [comment]
Adding this isn't planned. Though I would be happy to accept PRs

**Comment by lmirosevic** [comment]
Closing as interest seems low. LMK if not and I'll be happy to reopen.
