### ISSUE TITLE
Problematic PPI Default on iOS

### ISSUE THREAD

**Issue by cpsauer** [lmirosevic/GBDeviceInfo#89]
Hi! Thanks for creating such a useful library.

I just updated to the latest and noticed a somewhat problematic change. In the absence of PPI data on iOS, where the OS doesn't provide an easy lookup of the screen's PPI, we're falling back to the following code in GBDeviceInfo_iOS.m:
```
[UIFont systemFontOfSize:72].lineHeight
```

I was initially excited, thinking we'd found a future proof way of getting PPI on iOS...but on closer inspection, I think this doesn't do what the author intended. For example, on an iPhone X, that code returns 85.921875. The true PPI in the lookup table is 458... In general, it seems this code just creates a font with 72 point height and then gets its standard line spacing in points, with no relation to the physical height of the screen or pixels.

It feels like we should just revert out the else defining the default, if it doesn't have any particular relation to the true value. I'd suggest preserving the previous behavior of returning 0, over returning some wrong value, though we could do 153*[[UIScreen mainScreen] scale], to provide a better default. That'd be right for the iphone X family anyway, and about right for some older ones.

Would reverting be an okay change? Happy to submit the PR, if so.

Commits that introduced the issue:
https://github.com/lmirosevic/GBDeviceInfo/commit/47a221790b69e8466efa9bb75f9267a82f81a692
https://github.com/lmirosevic/GBDeviceInfo/commit/32a68f0b9b7f9424f12c454d558ce09d03e1d442

Thanks!

**Comment by lmirosevic** [comment]
Interesting. I tend to agree with you that showing a 0 value is better than the current indeterministic behaviour.

If you could submit a PR, that would be fantastic! I'll see that I cut a new release ASAP, seeing as this is indeterministic behaviour which isn't great.

Thanks!

**Comment by cpsauer** [comment]
Done.

**Comment by lmirosevic** [comment]
Pushed as `6.0.0`. Major version bump since this is technically a breaking change.

**Comment by lmirosevic** [comment]
Thanks for the PR!
