### ISSUE TITLE
Error to added 'GBDeviceInfo/Jailbreak'

### ISSUE THREAD

**Issue by paoloandrea** [lmirosevic/GBDeviceInfo#91]
Hi when I try to load your pod this way
```
pod 'GBDeviceInfo', '~> 5.5'
pod 'GBDeviceInfo / Jailbreak'
```
I receive the error below.
How can I solve?
Thank you

`[!] The 'Pods-MYPODS' target has transitive dependencies that include static binaries: (MY_DIR/Pods/GBJailbreakDetection/GBJailbreakDetection.framework)`

**Comment by lmirosevic** [comment]
You musn't use `use_frameworks`.

I'm very open to PRs to change this. In the meantime will close this issue.
