### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by santogioia** [lmirosevic/GBDeviceInfo#92]
I tried to include GBDeviceInfo in my Cartfile (including the line `github "lmirosevic/GBDeviceInfo" ~> 6.0` in the Cartfile, I also tried to add different lines in the Cartfile but it's always the same) but when I run `carthage update --platform ios` I get the following error:

Dependency "GBDeviceInfo" has no shared framework schemes for any of the platforms: iOS

What am I doing wrong to include this framework in my application through Carthage?

**Comment by lmirosevic** [comment]
Carthage support was never added to this library.

Closing this issue for now, but I'm more than happy to accept PRs which would add support for Carthage.

**Comment by santogioia** [comment]
I found out the problem. Carthage does not support "static libraries". A "static framework" is needed instead (.framework), I will try in the next days to create another target which can be used by Carthage.

**Comment by eduardbosch** [comment]
Updating the dependency from:
`github "lmirosevic/GBDeviceInfo" ~> 6.0`
to:
`github "lmirosevic/GBDeviceInfo" "master"`

Solves Carthage no shared framework schemes error.

This is related to this issue https://github.com/davbeck/TUSafariActivity/issues/22#issuecomment-481683427
